"""initial schema

Revision ID: 5975fa3bca56
Revises: 
Create Date: 2026-07-26 09:03:13.458671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5975fa3bca56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('mgmt_host', sa.String(), nullable=False),
    sa.Column('mgmt_port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('ha_state', sa.String(), nullable=True),
    sa.Column('ha_peer_serial', sa.String(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('licenses', sa.JSON(), nullable=False),
    sa.Column('connection_status', sa.String(), nullable=False),
    sa.Column('last_connectivity_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_config_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('config_change_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_name', sa.String(), nullable=False),
    sa.Column('element_xml', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('validation_warnings', sa.JSON(), nullable=False),
    sa.Column('impact_summary', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('commit_job_id', sa.String(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('interface_count', sa.Integer(), nullable=False),
    sa.Column('zone_count', sa.Integer(), nullable=False),
    sa.Column('object_count', sa.Integer(), nullable=False),
    sa.Column('policy_count', sa.Integer(), nullable=False),
    sa.Column('interfaces', sa.JSON(), nullable=False),
    sa.Column('zones', sa.JSON(), nullable=False),
    sa.Column('objects', sa.JSON(), nullable=False),
    sa.Column('policies', sa.JSON(), nullable=False),
    sa.Column('diff_summary', sa.JSON(), nullable=False),
    sa.Column('is_drift', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_events_occurred_at'), 'health_events', ['occurred_at'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('log_type', sa.String(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_device_id'), 'log_entries', ['device_id'], unique=False)
    op.create_index(op.f('ix_log_entries_log_type'), 'log_entries', ['log_type'], unique=False)
    op.create_index(op.f('ix_log_entries_logged_at'), 'log_entries', ['logged_at'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_recorded_at'), 'metrics', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_recorded_at'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_log_entries_logged_at'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_log_type'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_device_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_health_events_occurred_at'), table_name='health_events')
    op.drop_table('health_events')
    op.drop_table('config_versions')
    op.drop_table('config_change_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###
